---
- name: EOS Example
  gather_facts: False
  hosts: arista

  tasks:
    - name: Execute Show Command
      arista.eos.eos_command:
        commands: 
          - command: 'show ip route'
            output: 'json'
        # commands: show ip route | json
      register: show_vlan

