---
- name: Jinja2 Deploy
  hosts: nxos
  gather_facts: False
  tasks:
    - name: Generate interface configuration
      ansible.builtin.template:
        src: interfaces.j2
        dest: "./CFGS/{{ inventory_hostname }}/01-{{ inventory_hostname }}-intf.txt"

    - name: Generate BGP configuration
      ansible.builtin.template:
        src: bgp.j2
        dest: "./CFGS/{{ inventory_hostname }}/02-{{ inventory_hostname }}-bgp.txt"

    - name: Assemble the two parts into one configuration change file
      ansible.builtin.assemble:
        src: "./CFGS/{{ inventory_hostname }}/"
        dest: "./CFGS/{{ inventory_hostname }}-config.txt"

    - name: Deploy configurations to devices
      cisco.nxos.nxos_config:
        src: "./CFGS/{{ inventory_hostname }}-config.txt"

    - name: Verify BGP State
      cisco.nxos.nxos_command:
        commands: show ip bgp summary
      register: output
      tags: bgp_out

    - name: Show BGP Session
      ansible.builtin.debug:
        var: output.stdout_lines[0]
      tags: bgp_out
