---
- name: EOS Example (hierarchy)
  hosts: arista6
  gather_facts: False
  tasks:
    - name: Config with hierarchy
      arista.eos.eos_config:
        before: no interface Loopback99
        parents: interface Loopback99
        lines:
          - description * Test via Ansible *
          - ip address 172.16.31.1/32
          - ipv6 address 2001:db8:0:1::2/128
        match: line
        replace: block
