---
- name: IOS Example (hierarchy)
  hosts: cisco1
  gather_facts: False
  tasks:
    - name: Ensure interface exists
      cisco.ios.ios_config:
        lines:
          - interface Loopback99

    - name: Config with hierarchy
      cisco.ios.ios_config:
        before: no interface Loopback99
        parents: interface Loopback99
        lines:
          - ip address 172.16.31.1 255.255.255.0
          - description * Test via Ansible *
        match: line
        replace: block
