---
- name: Create VLAN and assign it to interface
  hosts: arista
  gather_facts: False
  tasks:
    - name: Create VLAN250
      arista.eos.eos_vlans:
        config:
          - name: "{{ vlan_name }}"
            vlan_id: "{{ vlan_id }}"
        state: merged

    - name: "Assign {{ intf_name }} to VLAN{{ vlan_id }}"
      arista.eos.eos_l2_interfaces:
        config:
          - name: "{{ intf_name }}"
            access:
              vlan: "{{ vlan_id }}"
        state: merged

    - name: Execute "show vlan" on Arista switches
      arista.eos.eos_command:
        commands: show vlan | json
      register: output

    - ansible.builtin.set_fact:
        interfaces_dict: '{{ output.stdout[0].vlans[vlan_id].interfaces }}'
        vlan_status: '{{ output.stdout[0].vlans[vlan_id].status }}'

    - name: "Verify VLAN is active and {{ intf_name }} is assigned to VLAN"
      ansible.builtin.assert:
        that:
          - vlan_status == 'active'
          - "'Ethernet7' in interfaces_dict" 
