---
- name: VLAN configuration
  hosts: arista5
  gather_facts: False
  tasks:
    - name: Merge provided configuration with device configuration
      arista.eos.eos_vlans:
        config:
          - name: Blue10
            vlan_id: 10
            state: active
          - name: Blue20
            vlan_id: 20
            state: active
          - name: Blue30
            vlan_id: 30
            state: active
        # state: merged
        state: replaced
