---
- name: "Exercise 1b"
  hosts: localhost
  tasks:
    - name: Loops, Include, and Dynamic Name (exercise1b)
      ansible.builtin.include_tasks: "{{ my_tasks }}"
      loop:
        - 10.1.1.1
        - 10.1.1.2
        - 10.1.1.3
        - 10.1.1.4
