---
- name: RegEx Example2
  hosts: cisco5
  gather_facts: False

  tasks:
    - name: Executing command
      cisco.ios.ios_command:
        commands: show ip int brief
      register: output

    - ansible.builtin.set_fact:
        output: "{{ output.stdout[0] }}"

    - name: Strip header information
      ansible.builtin.set_fact:
        show_ip: "{{ output | regex_replace('Interface.*Protocol') | trim }}"

    - name: Extract interface name
      ansible.builtin.debug:
        msg: "{{ item | regex_search('^\\S+') }}"
      loop: "{{ show_ip.splitlines() }}"
      loop_control:
        label: ""
