---
- name: RegEx Example3
  hosts: cisco5
  gather_facts: False

  tasks:
    - name: Executing command
      cisco.ios.ios_command:
        commands: show version
      register: output

    - ansible.builtin.set_fact:
        output: "{{ output.stdout[0] }}"

    - ansible.builtin.debug:
        msg: "{{ output.splitlines() }}"

    - name: Show Version (return capture group1)
      ansible.builtin.debug:
        msg: "{{ output | regex_search('^Processor board ID (\\S+).*$', '\\1', multiline=True) }}"

    - name: Show Version (return capture group-named)
      ansible.builtin.debug:
        msg: "{{ output | regex_search('^Processor board ID (?P<serial_num>\\S+).*$', '\\g<serial_num>', multiline=True) }}"

