---
- name: TextFSM Example4
  hosts: cisco5
  gather_facts: True
  vars:
    platform: "cisco_ios"
    command: "show ip int brief"

  tasks:
    - name: Executing command
      cisco.ios.ios_command:
        commands: "{{ command }}"
      register: output

    - ansible.builtin.set_fact:
       show_ip: "{{ output.stdout[0] | ntc_parse(command, platform) }}"

    - ansible.builtin.debug:
        var: show_ip
