---
- name: TextFSM Example2
  hosts: cisco5
  gather_facts: False
  vars:
    fsm_template: "cisco_ios_show_ip_interface_brief.template"

  roles:
    - ansible-network.network-engine

  tasks:
    - name: Executing command
      cisco.ios.ios_command:
        commands: show ip int brief
      register: output

    - ansible.builtin.set_fact:
        show_ip: "{{ output.stdout[0] }}"

    # Only abbreviated name works: needs migrated to 'cli_parse'
    - name: TextFSM test
      textfsm_parser:
        file: "{{ fsm_template }}"
        content: "{{ show_ip }}"
        name: show_ip_parsed

    - ansible.builtin.debug:
        var: show_ip_parsed
