---
- name: TextFSM Example3
  hosts: cisco5
  gather_facts: True
  vars:
    platform: "cisco_ios"
    command: "show ip int brief"
    # ntc-templates >= 2.x changed this
    textfsm_rel_path: "ntc-templates/ntc_templates/templates"

  tasks:
    - name: Executing command
      cisco.ios.ios_command:
        commands: "{{ command }}"
      register: output

    - ansible.builtin.debug:
        var: output

    # This is only needed so our automated tests work properly
    - name: "Set home directory as ntc_parse doesn't understand ~"
      ansible.builtin.set_fact:
        textfsm_index: "{{ inventory_dir }}/{{textfsm_rel_path }}"

    - ansible.builtin.set_fact:
       show_ip: "{{ output.stdout[0] | ntc_parse(command, platform, textfsm_index ) }}"

    - ansible.builtin.debug:
        var: show_ip
