---

- name: Invalid indentation
  hosts: nxos1
  gather_facts: False

  tasks:
    - name: Invalid indentation
      cisco.nxos.nxos_command:
        commands: show interface
         wait_for: True
      register: output
