---

- name: Invalid cmd
  hosts: nxos1
  gather_facts: False

  tasks:
    - name: Executing invalid command
      cisco.nxos.nxos_command:
        commands: show bogus
      register: output

    - ansible.builtin.debug:
        var: output
