---

- name: Using a string literal and not variable
  hosts: nxos1
  gather_facts: False

  tasks:
    - name: Executing cmd
      cisco.nxos.nxos_command:
        commands: show interface
      register: output

    - name: 'Print a string literal named "output"'
      ansible.builtin.debug:
        msg: output
