- name: Print Hello
  ansible.builtin.debug:
    msg: "Hello1"
  tags: foo1

- name: Print Hello
  ansible.builtin.debug:
    msg: "Hello2"
  tags: foo2

- name: Print Hello
  ansible.builtin.debug:
    msg: "Hello3"
  tags: foo3
