---
- name: Example3
  hosts: arista
  gather_facts: True
  tasks:
    # - ansible.builtin.debug:
    #    var: ansible_facts

    - name: name-server for EOS
      arista.eos.eos_config:
        lines:
          - "ip name-server vrf default {{ dns_server1 }}"
          - "ip name-server vrf default {{ dns_server2 }}"
        save_when: changed
      when: ansible_facts.net_system == "eos"

