---
- name: NXOS Config Change
  hosts: nxos
  gather_facts: False
  vars:
    ansible_connection: httpapi
    # Set in inventory
    # ansible_httpapi_use_ssl=True
    # ansible_httpapi_validate_certs=False
    # ansible_httpapi_port=8443

  tasks:
    - cisco.nxos.nxos_config:
        lines:
          - "ip domain-name {{ domain_name }}"
          - "ip name-server {{ dns_server1 }} {{ dns_server2 }}"
          - "ntp server {{ ntp_server1 }} use-vrf management"
          - "ntp server {{ ntp_server2 }} use-vrf default"


