---
- hosts: cisco
  tasks:
    - name: Import IOS tasks
      ansible.builtin.import_tasks: ios-tasks.yml
      when: ansible_facts.net_iostype == "IOS"

    - name: Import IOS-XE tasks
      ansible.builtin.import_tasks: ios-xe-tasks.yml
      when: ansible_facts.net_iostype == "IOS-XE"
