- name: Interface configuration
  hosts: nxos1
  gather_facts: False
  tasks:
    - name: Update interface config
      cisco.nxos.nxos_interfaces:
        config:
          - name: Ethernet1/4
            description: 'Testing Ansible configuration'
            enabled: False
        state: merged

    - name: Configure ports to be switchports
      cisco.nxos.nxos_interfaces:
        config:
          - name: "{{ item }}"
            enabled: True
            mode: layer2
      loop:
        - Ethernet1/3
        - Ethernet1/4
      tags: switchport
