---
- name: Exercise1
  hosts: arista
  gather_facts: False

  tasks:
    - name: Executing command
      arista.eos.eos_command:
        commands: show ip arp
      register: output

    - ansible.builtin.set_fact:
        show_arp: "{{ output.stdout[0] }}"

    - ansible.builtin.debug:
        msg: "{{ show_arp | show_ip_arp }}"
