---
- name: Test Jinja2
  hosts: cisco1
  gather_facts: False
  vars:
    dhcp: True
    dhcp_exclude1_start: 192.168.200.100
    dhcp_exclude1_end: 192.168.200.199
    dhcp_network: 192.168.200.0
    dhcp_netmask: 255.255.255.0
    dhcp_gateway: 192.168.200.1
  tasks:
    - ansible.builtin.template:
        src: dhcp_config.j2
        dest: "./CFGS/{{ inventory_hostname }}-dhcp.txt"
