---
- name: Loop exercise1
  hosts: local
  vars:
    sf_ip_addr:
      - 10.1.1.1
      - 10.1.1.2
      - 10.1.1.3
      - 10.1.1.4
    dallas_ip_addr:
      - 10.2.1.1
      - 10.2.1.2
      - 10.2.1.3
      - 10.2.1.4

  tasks:
    - name: SF and Dallas IP addresses
      ansible.builtin.debug:
        msg: "{{ item }}"
      loop: "{{ sf_ip_addr }} + {{ dallas_ip_addr }}"

