---
- hosts: local
  tasks:
    - name: "Import (static) - loops fail"
      ansible.builtin.import_tasks: common_tasks.yml
      # ansible.builtin.import_tasks: common_tasks_w_loop.yml
      loop:
        - 10.1.1.1
        - 10.1.1.2
        - 10.1.1.3
        - 10.1.1.4

    - name: "Include (dynamic) - loops work"
      ansible.builtin.include_tasks: common_tasks.yml
      loop:
        - 10.1.1.1
        - 10.1.1.2
        - 10.1.1.3
        - 10.1.1.4

