---
- name: RM Facts
  hosts: cisco1
  gather_facts: True
  module_defaults:
    ios_facts:
      gather_network_resources:
        - "!lacp"
        - all
        # - vlans
        # - interfaces
        # - l2_interfaces
        # - l3_interfaces
        # - lacp
        # - lldp_global
        # - lldp_interfaces
        # - lag_interfaces

  tasks:
    - name: Display network resources
      ansible.builtin.debug:
        var: ansible_network_resources
