---
- name: RM Facts
  hosts: nxos2
  gather_facts: True
  module_defaults:
    nxos_facts:
      gather_network_resources:
        # - vlans
        - interfaces
        - l2_interfaces
        - l3_interfaces
        # - lacp
        # - lldp_global
        # - lldp_interfaces (not available on NX-OS)
        # - lag_interfaces

  tasks:
    - name: Test
      ansible.builtin.debug:
        var: ansible_network_resources
